/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Includes.h"
/* Header for class org_jouvieje_fmoddesigner_defines_VersionsJNI */

#ifndef _Included_org_jouvieje_fmoddesigner_defines_VersionsJNI
#define _Included_org_jouvieje_fmoddesigner_defines_VersionsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_fmoddesigner_defines_VersionsJNI
 * Method:    get_FMOD_EVENT_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_defines_VersionsJNI_get_1FMOD_1EVENT_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_defines_VersionsJNI
 * Method:    get_FMOD_EVENT_NET_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_defines_VersionsJNI_get_1FMOD_1EVENT_1NET_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_defines_VersionsJNI
 * Method:    get_NATIVEFMODDESIGNER_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_defines_VersionsJNI_get_1NATIVEFMODDESIGNER_1VERSION
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
