/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_fmoddesigner_FmodDesignerJNI */

#ifndef _Included_org_jouvieje_fmoddesigner_FmodDesignerJNI
#define _Included_org_jouvieje_fmoddesigner_FmodDesignerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_SIZEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1SIZEOF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_newArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1newArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_release
 * Signature: (JZZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1release
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_stop
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1stop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/fmodex/utils/Pointer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getState
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getState
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getParentGroup
 * Signature: (JLorg/jouvieje/fmoddesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getParentGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getChannelGroup
 * Signature: (JLorg/jouvieje/fmodex/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getChannelGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setCallback
 * Signature: (JZJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setCallback
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getParameter
 * Signature: (J[BLorg/jouvieje/fmoddesigner/EventParameter;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getParameter
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getParameterByIndex
 * Signature: (JILorg/jouvieje/fmoddesigner/EventParameter;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getParameterByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getNumParameters
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getNumParameters
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getProperty
 * Signature: (J[BJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getProperty
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getPropertyByIndex
 * Signature: (JIJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getPropertyByIndex
  (JNIEnv *, jclass, jlong, jint, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setProperty
 * Signature: (J[BJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setProperty
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setPropertyByIndex
 * Signature: (JIJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setPropertyByIndex
  (JNIEnv *, jclass, jlong, jint, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getNumProperties
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getNumProperties
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getPropertyInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/fmodex/utils/Pointer;Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getPropertyInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getCategory
 * Signature: (JLorg/jouvieje/fmoddesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getCategory
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setPitch
 * Signature: (JFI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setPitch
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getPitch
 * Signature: (JLjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getPitch
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setMute
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getMute
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getMute
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_set3DAttributes
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1set3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_get3DAttributes
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1get3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_set3DOcclusion
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1set3DOcclusion
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_get3DOcclusion
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1get3DOcclusion
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    Event_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_Event_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getCategory
 * Signature: (J[BLorg/jouvieje/fmoddesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getCategory
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getCategoryByIndex
 * Signature: (JILorg/jouvieje/fmoddesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getCategoryByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getNumCategories
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getNumCategories
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getEventByIndex
 * Signature: (JIILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getEventByIndex
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getNumEvents
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getNumEvents
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getParentCategory
 * Signature: (JLorg/jouvieje/fmoddesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getParentCategory
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_stopAllEvents
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1stopAllEvents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_setPitch
 * Signature: (JFI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1setPitch
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getPitch
 * Signature: (JLjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getPitch
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_setMute
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1setMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getMute
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getMute
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getChannelGroup
 * Signature: (JLorg/jouvieje/fmodex/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getChannelGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventCategory_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventCategory_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_loadEventData
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1loadEventData
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_freeEventData
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1freeEventData
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getGroup
 * Signature: (J[BZLorg/jouvieje/fmoddesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getGroup
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getGroupByIndex
 * Signature: (JIZLorg/jouvieje/fmoddesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getGroupByIndex
  (JNIEnv *, jclass, jlong, jint, jboolean, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getParentGroup
 * Signature: (JLorg/jouvieje/fmoddesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getParentGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getParentProject
 * Signature: (JLorg/jouvieje/fmoddesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getParentProject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getNumGroups
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getNumGroups
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getEvent
 * Signature: (J[BILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getEvent
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getEventByIndex
 * Signature: (JIILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getEventByIndex
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getNumEvents
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getNumEvents
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getProperty
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getProperty
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getPropertyByIndex
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getPropertyByIndex
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getNumProperties
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getNumProperties
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getState
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getState
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventGroup_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventGroup_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_getRange
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1getRange
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_setValue
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1setValue
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_getValue
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1getValue
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_setVelocity
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1setVelocity
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_getVelocity
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1getVelocity
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_setSeekSpeed
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1setSeekSpeed
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_getSeekSpeed
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1getSeekSpeed
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_keyOff
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1keyOff
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventParameter_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventParameter_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getGroup
 * Signature: (J[BZLorg/jouvieje/fmoddesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getGroup
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getGroupByIndex
 * Signature: (JIZLorg/jouvieje/fmoddesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getGroupByIndex
  (JNIEnv *, jclass, jlong, jint, jboolean, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getNumGroups
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getNumGroups
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getEvent
 * Signature: (J[BILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getEvent
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getEventByProjectID
 * Signature: (JIILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getEventByProjectID
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getNumEvents
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getNumEvents
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_loadSampleData
 * Signature: (JLjava/nio/IntBuffer;JILorg/jouvieje/fmodex/utils/Pointer;II)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1loadSampleData
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jint, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_stopAllEvents
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1stopAllEvents
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventProject_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventProject_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_SIZEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1SIZEOF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_newArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1newArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_add
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1add
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_remove
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1remove
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_removeHead
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1removeHead
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_clear
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1clear
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_findFirstEntry
 * Signature: (JLorg/jouvieje/fmoddesigner/EventQueueEntry;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1findFirstEntry
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_findNextEntry
 * Signature: (JLorg/jouvieje/fmoddesigner/EventQueueEntry;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1findNextEntry
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_includeDuckingCategory
 * Signature: (JJFFII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1includeDuckingCategory
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jint, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_excludeDuckingCategory
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1excludeDuckingCategory
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_setCallback
 * Signature: (JZJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1setCallback
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_dump
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1dump
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueue_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueue_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getInfoOnlyEvent
 * Signature: (JLorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getInfoOnlyEvent
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getRealEvent
 * Signature: (JLorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getRealEvent
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_setPriority
 * Signature: (JC)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1setPriority
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getPriority
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getPriority
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_setExpiryTime
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1setExpiryTime
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getExpiryTime
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getExpiryTime
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_setDelayTime
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1setDelayTime
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getDelayTime
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getDelayTime
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_setInterrupt
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1setInterrupt
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getInterrupt
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getInterrupt
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_setCrossfadeTime
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1setCrossfadeTime
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getCrossfadeTime
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getCrossfadeTime
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventQueueEntry_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventQueueEntry_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_set3DAttributes
 * Signature: (JJFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1set3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_get3DAttributes
 * Signature: (JJLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1get3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_setProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1setProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_getProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1getProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_setActive
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1setActive
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_getActive
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1getActive
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventReverb_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventReverb_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_init
 * Signature: (JIIJI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1init
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_update
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1update
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_setMediaPath
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1setMediaPath
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_setPluginPath
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1setPluginPath
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getVersion
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getVersion
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getInfo
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getInfo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getSystemObject
 * Signature: (JLorg/jouvieje/fmodex/System;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getSystemObject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getMusicSystem
 * Signature: (JLorg/jouvieje/fmoddesigner/MusicSystem;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getMusicSystem
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_load
 * Signature: (J[BJLorg/jouvieje/fmoddesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1load__J_3BJLorg_jouvieje_fmoddesigner_EventProject_2
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_load
 * Signature: (JLjava/nio/ByteBuffer;JJLorg/jouvieje/fmoddesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1load__JLjava_nio_ByteBuffer_2JJLorg_jouvieje_fmoddesigner_EventProject_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_unload
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1unload
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getProject
 * Signature: (J[BLorg/jouvieje/fmoddesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getProject
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getProjectByIndex
 * Signature: (JILorg/jouvieje/fmoddesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getProjectByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getNumProjects
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getNumProjects
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getCategory
 * Signature: (J[BLorg/jouvieje/fmoddesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getCategory
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getCategoryByIndex
 * Signature: (JILorg/jouvieje/fmoddesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getCategoryByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getMusicCategory
 * Signature: (JLorg/jouvieje/fmoddesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getMusicCategory
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getNumCategories
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getNumCategories
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getGroup
 * Signature: (J[BZLorg/jouvieje/fmoddesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getGroup
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getEvent
 * Signature: (J[BILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getEvent
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getEventBySystemID
 * Signature: (JIILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getEventBySystemID
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getEventByGUID
 * Signature: (JJILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getEventByGUID
  (JNIEnv *, jclass, jlong, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getEventByGUIDString
 * Signature: (J[BILorg/jouvieje/fmoddesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getEventByGUIDString
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getNumEvents
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getNumEvents
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_setReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1setReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getReverbPreset
 * Signature: (J[BJLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getReverbPreset
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getReverbPresetByIndex
 * Signature: (JIJLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getReverbPresetByIndex
  (JNIEnv *, jclass, jlong, jint, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getNumReverbPresets
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getNumReverbPresets
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_createReverb
 * Signature: (JLorg/jouvieje/fmoddesigner/EventReverb;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1createReverb
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_setReverbAmbientProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1setReverbAmbientProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getReverbAmbientProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getReverbAmbientProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_createEventQueue
 * Signature: (JLorg/jouvieje/fmoddesigner/EventQueue;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1createEventQueue
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_createEventQueueEntry
 * Signature: (JJLorg/jouvieje/fmoddesigner/EventQueueEntry;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1createEventQueueEntry
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_set3DNumListeners
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1set3DNumListeners
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_get3DNumListeners
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1get3DNumListeners
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_set3DListenerAttributes
 * Signature: (JIJJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1set3DListenerAttributes
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_get3DListenerAttributes
 * Signature: (JIJJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1get3DListenerAttributes
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getUserData
 * Signature: (JLorg/jouvieje/fmodex/utils/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_preloadFSB
 * Signature: (J[BIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1preloadFSB
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_unloadFSB
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1unloadFSB
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    EventSystem_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_EventSystem_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    FmodDesigner_EventSystem_Create
 * Signature: (Lorg/jouvieje/fmoddesigner/EventSystem;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_FmodDesigner_1EventSystem_1Create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    FmodDesigner_NetEventSystem_Init
 * Signature: (JS)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_FmodDesigner_1NetEventSystem_1Init
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    FmodDesigner_NetEventSystem_Update
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_FmodDesigner_1NetEventSystem_1Update
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    FmodDesigner_NetEventSystem_Shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_FmodDesigner_1NetEventSystem_1Shutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    FmodDesigner_NetEventSystem_GetVersion
 * Signature: (Ljava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_FmodDesigner_1NetEventSystem_1GetVersion
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicPrompt_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicPrompt_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicPrompt_begin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicPrompt_1begin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicPrompt_end
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicPrompt_1end
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicPrompt_isActive
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicPrompt_1isActive
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicPrompt_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicPrompt_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_SIZEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1SIZEOF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_newArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1newArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_setReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1setReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_setMute
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1setMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getMute
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getMute
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getInfo
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getInfo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_promptCue
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1promptCue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_prepareCue
 * Signature: (JILorg/jouvieje/fmoddesigner/MusicPrompt;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1prepareCue
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getParameterValue
 * Signature: (JILjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getParameterValue
  (JNIEnv *, jclass, jlong, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_setParameterValue
 * Signature: (JIF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1setParameterValue
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getCues
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getCues
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getNextCue
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getNextCue
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getParameters
 * Signature: (JJ[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getParameters
  (JNIEnv *, jclass, jlong, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getNextParameter
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getNextParameter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_loadSoundData
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1loadSoundData
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_freeSoundData
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1freeSoundData
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_setCallback
 * Signature: (JZJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1setCallback
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_FmodDesignerJNI
 * Method:    MusicSystem_getMemoryInfo
 * Signature: (JIILjava/nio/IntBuffer;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_FmodDesignerJNI_MusicSystem_1getMemoryInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
