/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_fmoddesigner_structures_StructureJNI */

#ifndef _Included_org_jouvieje_fmoddesigner_structures_StructureJNI
#define _Included_org_jouvieje_fmoddesigner_structures_StructureJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_memoryused
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1memoryused
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_set_memoryused
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1set_1memoryused
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_positionms
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1positionms
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_lengthms
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1lengthms
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_channelsplaying
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1channelsplaying
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_instancesactive
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1instancesactive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_maxwavebanks
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1maxwavebanks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_wavebankinfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1wavebankinfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_set_wavebankinfo
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1set_1wavebankinfo
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_projectid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1projectid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_systemid
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1systemid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_audibility
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1audibility
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_numinstances
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1numinstances
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_instances
 * Signature: (J)[Lorg/jouvieje/fmoddesigner/Event;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1instances
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_set_instances
 * Signature: (J[Lorg/jouvieje/fmoddesigner/Event;)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1set_1instances
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_INFO_get_guid
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1INFO_1get_1guid
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_get_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1get_1size
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_set_size
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1set_1size
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_get_encryptionkey
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1get_1encryptionkey
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_set_encryptionkey
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1set_1encryptionkey
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_get_sounddefentrylimit
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1get_1sounddefentrylimit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_set_sounddefentrylimit
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1set_1sounddefentrylimit
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_get_loadfrommemory_length
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1get_1loadfrommemory_1length
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_set_loadfrommemory_length
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1set_1loadfrommemory_1length
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_get_override_category_vals
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1get_1override_1category_1vals
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_set_override_category_vals
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1set_1override_1category_1vals
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_get_sizeof_instancepool_simple
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1get_1sizeof_1instancepool_1simple
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_LOADINFO_set_sizeof_instancepool_simple
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1LOADINFO_1set_1sizeof_1instancepool_1simple
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SOUNDDEFINFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SOUNDDEFINFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SOUNDDEFINFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SOUNDDEFINFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SOUNDDEFINFO_get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SOUNDDEFINFO_1get_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SOUNDDEFINFO_get_numentries
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SOUNDDEFINFO_1get_1numentries
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SOUNDDEFINFO_get_entrynames
 * Signature: (J)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SOUNDDEFINFO_1get_1entrynames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SOUNDDEFINFO_get_entrytypes
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SOUNDDEFINFO_1get_1entrytypes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_get_numevents
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1get_1numevents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_get_numinstances
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1get_1numinstances
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_get_maxwavebanks
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1get_1maxwavebanks
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_get_wavebankinfo
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1get_1wavebankinfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_set_wavebankinfo
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1set_1wavebankinfo
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_get_numplayingevents
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1get_1numplayingevents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_get_playingevents
 * Signature: (J)[Lorg/jouvieje/fmoddesigner/Event;
 */
JNIEXPORT jobjectArray JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1get_1playingevents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_SYSTEMINFO_set_playingevents
 * Signature: (J[Lorg/jouvieje/fmoddesigner/Event;)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1SYSTEMINFO_1set_1playingevents
  (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_SIZEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1SIZEOF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_newArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1newArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_name
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_streamrefcnt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1streamrefcnt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_samplerefcnt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1samplerefcnt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_numstreams
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1numstreams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_maxstreams
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1maxstreams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_streamsinuse
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1streamsinuse
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_streammemory
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1streammemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_samplememory
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1samplememory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_EVENT_WAVEBANKINFO_get_type
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1EVENT_1WAVEBANKINFO_1get_1type
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ENTITY_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ENTITY_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ENTITY_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ENTITY_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ENTITY_get_name
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ENTITY_1get_1name
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ENTITY_set_name
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ENTITY_1set_1name
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ENTITY_get_id
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ENTITY_1get_1id
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ENTITY_set_id
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ENTITY_1set_1id
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_INFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1INFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_INFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1INFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_INFO_get_starving
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1INFO_1get_1starving
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ITERATOR_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ITERATOR_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ITERATOR_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ITERATOR_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ITERATOR_get_value
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ITERATOR_1get_1value
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ITERATOR_set_value
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ITERATOR_1set_1value
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ITERATOR_get_filter
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ITERATOR_1get_1filter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_ITERATOR_set_filter
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1ITERATOR_1set_1filter
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_SAMPLE_INFO_new
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1SAMPLE_1INFO_1new
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_SAMPLE_INFO_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1SAMPLE_1INFO_1delete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_SAMPLE_INFO_get_segment_id
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1SAMPLE_1INFO_1get_1segment_1id
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_SAMPLE_INFO_set_segment_id
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1SAMPLE_1INFO_1set_1segment_1id
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_SAMPLE_INFO_get_index
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1SAMPLE_1INFO_1get_1index
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_SAMPLE_INFO_set_index
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1SAMPLE_1INFO_1set_1index
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_SAMPLE_INFO_get_filename
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1SAMPLE_1INFO_1get_1filename
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_fmoddesigner_structures_StructureJNI
 * Method:    FMOD_MUSIC_SAMPLE_INFO_set_filename
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmoddesigner_structures_StructureJNI_FMOD_1MUSIC_1SAMPLE_1INFO_1set_1filename
  (JNIEnv *, jclass, jlong, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
