/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Includes.h"
/* Header for class org_jouvieje_fmodex_Init */

#ifndef _Included_org_jouvieje_fmodex_Init
#define _Included_org_jouvieje_fmodex_Init
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_fmodex_Init
 * Method:    attachJavaVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_fmodex_Init_attachJavaVM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
