/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Includes.h"
/* Header for class org_jouvieje_fmodex_defines_VersionsJNI */

#ifndef _Included_org_jouvieje_fmodex_defines_VersionsJNI
#define _Included_org_jouvieje_fmodex_defines_VersionsJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_fmodex_defines_VersionsJNI
 * Method:    get_FMOD_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmodex_defines_VersionsJNI_get_1FMOD_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmodex_defines_VersionsJNI
 * Method:    get_NATIVEFMODEX_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmodex_defines_VersionsJNI_get_1NATIVEFMODEX_1VERSION
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
