/* DO NOT EDIT THIS FILE - it is machine generated */
#include "Includes.h"
/* Header for class org_jouvieje_fmoddesigner_enumerations_EnumerationJNI */

#ifndef _Included_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
#define _Included_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_TYPE_FLOAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1TYPE_1FLOAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_TYPE_STRING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1TYPE_1STRING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTQUEUE_CALLBACKTYPE_PREPARE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTQUEUE_1CALLBACKTYPE_1PREPARE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTQUEUE_CALLBACKTYPE_ABOUTTOPLAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTQUEUE_1CALLBACKTYPE_1ABOUTTOPLAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTQUEUE_CALLBACKTYPE_FINISHED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTQUEUE_1CALLBACKTYPE_1FINISHED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTQUEUE_CALLBACKTYPE_EXPIRED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTQUEUE_1CALLBACKTYPE_1EXPIRED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_SYNCPOINT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1SYNCPOINT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_START
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1SOUNDDEF_1START
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_END
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1SOUNDDEF_1END
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_STOLEN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1STOLEN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_EVENTFINISHED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1EVENTFINISHED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_NET_MODIFIED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1NET_1MODIFIED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_CREATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1SOUNDDEF_1CREATE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_RELEASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1SOUNDDEF_1RELEASE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_INFO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1SOUNDDEF_1INFO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_EVENTSTARTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1EVENTSTARTED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_SOUNDDEF_SELECTINDEX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1SOUNDDEF_1SELECTINDEX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_CALLBACKTYPE_OCCLUSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1CALLBACKTYPE_1OCCLUSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_PITCHUNITS_OCTAVES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1PITCHUNITS_1OCTAVES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_PITCHUNITS_SEMITONES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1PITCHUNITS_1SEMITONES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_PITCHUNITS_TONES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1PITCHUNITS_1TONES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_VOLUME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1VOLUME
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_VOLUMERANDOMIZATION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1VOLUMERANDOMIZATION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PITCH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PITCH
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PITCH_OCTAVES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PITCH_1OCTAVES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PITCH_SEMITONES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PITCH_1SEMITONES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PITCH_TONES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PITCH_1TONES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PITCHRANDOMIZATION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PITCHRANDOMIZATION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_OCTAVES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PITCHRANDOMIZATION_1OCTAVES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_SEMITONES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PITCHRANDOMIZATION_1SEMITONES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PITCHRANDOMIZATION_TONES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PITCHRANDOMIZATION_1TONES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_PRIORITY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1PRIORITY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_MAX_PLAYBACKS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1MAX_1PLAYBACKS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_MAX_PLAYBACKS_BEHAVIOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1MAX_1PLAYBACKS_1BEHAVIOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_MODE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1MODE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_IGNORE_GEOMETRY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1IGNORE_1GEOMETRY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_ROLLOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1ROLLOFF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_MINDISTANCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1MINDISTANCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_MAXDISTANCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1MAXDISTANCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_POSITION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1POSITION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_CONEINSIDEANGLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1CONEINSIDEANGLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_CONEOUTSIDEANGLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1CONEOUTSIDEANGLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_CONEOUTSIDEVOLUME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1CONEOUTSIDEVOLUME
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_DOPPLERSCALE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1DOPPLERSCALE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_SPEAKERSPREAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1SPEAKERSPREAD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_PANLEVEL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1PANLEVEL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPEAKER_L
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPEAKER_1L
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPEAKER_C
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPEAKER_1C
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPEAKER_R
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPEAKER_1R
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPEAKER_LS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPEAKER_1LS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPEAKER_RS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPEAKER_1RS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPEAKER_LR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPEAKER_1LR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPEAKER_RR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPEAKER_1RR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPEAKER_LFE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPEAKER_1LFE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_REVERBWETLEVEL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1REVERBWETLEVEL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_ONESHOT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1ONESHOT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_FADEIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1FADEIN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_FADEOUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1FADEOUT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_REVERBDRYLEVEL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1REVERBDRYLEVEL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_TIMEOFFSET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1TIMEOFFSET
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPAWNINTENSITY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPAWNINTENSITY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_SPAWNINTENSITY_RANDOMIZATION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1SPAWNINTENSITY_1RANDOMIZATION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_WII_CONTROLLERSPEAKERS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1WII_1CONTROLLERSPEAKERS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_3D_POSRANDOMIZATION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_13D_1POSRANDOMIZATION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_EVENTTYPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1EVENTTYPE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_STEAL_PRIORITY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1STEAL_1PRIORITY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_EFFECTS_AFFECT_REVERB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1EFFECTS_1AFFECT_1REVERB
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_WILL_TERMINATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1WILL_1TERMINATE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENTPROPERTY_USER_BASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENTPROPERTY_1USER_1BASE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_RESOURCE_STREAMS_AND_SAMPLES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1RESOURCE_1STREAMS_1AND_1SAMPLES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_RESOURCE_STREAMS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1RESOURCE_1STREAMS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_RESOURCE_SAMPLES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1RESOURCE_1SAMPLES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_SOUNDDEF_ENTRYTYPE_WAVETABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1SOUNDDEF_1ENTRYTYPE_1WAVETABLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_SOUNDDEF_ENTRYTYPE_OSCILLATOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1SOUNDDEF_1ENTRYTYPE_1OSCILLATOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_SOUNDDEF_ENTRYTYPE_NULL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1SOUNDDEF_1ENTRYTYPE_1NULL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_EVENT_SOUNDDEF_ENTRYTYPE_PROGRAMMER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1EVENT_1SOUNDDEF_1ENTRYTYPE_1PROGRAMMER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_MUSIC_CALLBACKTYPE_SEGMENT_START
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1MUSIC_1CALLBACKTYPE_1SEGMENT_1START
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_MUSIC_CALLBACKTYPE_SEGMENT_END
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1MUSIC_1CALLBACKTYPE_1SEGMENT_1END
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_MUSIC_CALLBACKTYPE_SAMPLE_CREATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1MUSIC_1CALLBACKTYPE_1SAMPLE_1CREATE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_MUSIC_CALLBACKTYPE_SAMPLE_RELEASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1MUSIC_1CALLBACKTYPE_1SAMPLE_1RELEASE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_MUSIC_CALLBACKTYPE_RESET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1MUSIC_1CALLBACKTYPE_1RESET
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_fmoddesigner_enumerations_EnumerationJNI
 * Method:    get_FMOD_MUSIC_CALLBACKTYPE_BEAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_fmoddesigner_enumerations_EnumerationJNI_get_1FMOD_1MUSIC_1CALLBACKTYPE_1BEAT
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
